### ISSUE TITLE
prismjs line numbers and language toolbar not visible

### ISSUE THREAD

**Issue by daniellwdb** [daniellwdb/website#3]
Page: https://www.daniell.dev/blog/type-safe-i18n-with-typescript
On first load, code snippets do not have line numbers and the language of the snippet is not displayed, it does show after refreshing a couple of times:
![image](https://user-images.githubusercontent.com/44723767/118191549-097f1a80-b445-11eb-8750-54f661676858.png)

**Comment by daniellwdb** [comment]
Relevant files / line numbers: 
- https://github.com/daniellwdb/website/blob/development/pages/_app.tsx#L12-L23
- https://github.com/daniellwdb/website/blob/development/pages/blog/%5Bslug%5D.tsx#L146-L152

**Comment by puremana** [comment]
The issue is the classes aren't getting added.

`<pre class="notion-code">` is what it is loaded when the line numbers and language doesn't show.
`<pre class="notion-code language-typescript line-numbers">` is the same element when they do show.

Perhaps a race condition?

**Comment by daniellwdb** [comment]
That’s interesting, thanks for checking!
